import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="flex flex-col items-center">
            <h1 className="text-4xl font-bold">Hello World!</h1>
            <p className="mt-4 text-lg">Welcome to your new app!</p>
            <p>Soumouli</p>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
